#  Agentic YouTube Video Quality Analysis
## Notebook 01 — Collecte de Données (YouTube Data API v3)
## Contexte : Vidéos Éducatives Cameroun (3ème, Première, Terminale)

**Objectif** : Collecter des vidéos YouTube et leurs commentaires sur les matières scolaires
camerounaises (systèmes francophone et anglophone), avec optimisation stricte du quota API.

**Systèmes scolaires** : Francophone (BEPC/Bac) + Anglophone (GCE O/A-Level)

**Pipeline :**
1. Configuration & imports
2. Cache et utilitaires
3. Couche API YouTube
4. Phase B — Recherche des vidéos candidates
5. Phase C — Déduplication
6. Phase D — Enrichissement des métadonnées (batch)
7. Phase E — Filtrage qualité
8. Phase F — Collecte des commentaires
9. Résumé & vérification du dataset final

> Seed : 42 — Reproductible par tout tiers (NFR-02)

## 1 - Imports globaux

In [27]:
import os
import re
import sys
import json
import time
import logging
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple
import subprocess
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
import requests

print("Tous les imports effectués")
print(f"   pandas  : {pd.__version__}")
print(f"   numpy   : {np.__version__}")
print(f"   requests: {requests.__version__}")

Tous les imports effectués
   pandas  : 2.2.3
   numpy   : 1.26.4
   requests: 2.32.3

## 2 — Configuration centrale

In [14]:
#  URLs des endpoints API
YOUTUBE_API_KEY          = "AIzaSyA3xSd_QcscoUb9h8Xo1y7_MwU_wKZqyjo"
YOUTUBE_API_BASE_URL     = "https://www.googleapis.com/youtube/v3"
ENDPOINT_SEARCH          = f"{YOUTUBE_API_BASE_URL}/search"
ENDPOINT_VIDEOS          = f"{YOUTUBE_API_BASE_URL}/videos"
ENDPOINT_COMMENT_THREADS = f"{YOUTUBE_API_BASE_URL}/commentThreads"

# Langues cibles
LANGUES_CIBLES = ["fr", "en"]

# ─── Requêtes de recherche — Contexte éducatif Cameroun ───────────────
# Structure : { thematique: { level: { langue: [requetes] } } }
REQUETES_PAR_THEMATIQUE = {
    "mathematiques": {
        "troisieme": {
            "fr": [
                "mathématiques 3ème Cameroun",
                "cours maths troisième BEPC Cameroun",
                "exercices maths 3ème Cameroun corrigés",
                "algèbre 3ème Cameroun",
                "BEPC mathématiques Cameroun révision",
            ],
        },
        "premiere": {
            "fr": [
                "mathématiques Première Cameroun",
                "cours maths Première C D Cameroun",
                "Probatoire maths Cameroun",
                "dérivées fonctions Première Cameroun",
                "probabilités Première Cameroun",
            ],
        },
        "terminale": {
            "fr": [
                "mathématiques Terminale Cameroun",
                "intégrales Terminale Cameroun",
                "Baccalauréat maths Cameroun",
                "nombres complexes Terminale Cameroun",
                "révision bac maths Cameroun",
            ],
        },
        "form4_5": {
            "en": [
                "mathematics Form 4 Cameroon",
                "GCE O-Level maths Cameroon",
                "algebra Form 4 Cameroon",
                "O-Level mathematics revision Cameroon",
            ],
        },
        "lower6th": {
            "en": [
                "A-Level mathematics Lower 6 Cameroon",
                "calculus Lower 6th Cameroon",
                "pure mathematics A-Level Cameroon",
            ],
        },
        "upper6th": {
            "en": [
                "A-Level mathematics Upper 6 Cameroon",
                "integration Upper 6th Cameroon",
                "GCE A-Level revision maths Cameroon",
                "A-Level maths past questions Cameroon",
            ],
        },
    },
    "svt_sciences": {
        "troisieme": {
            "fr": [
                "SVT 3ème Cameroun",
                "BEPC SVT Cameroun révision",
                "biologie 3ème Cameroun cours",
                "génétique 3ème Cameroun",
            ],
        },
        "premiere": {
            "fr": [
                "SVT Première Cameroun",
                "Probatoire SVT Cameroun",
                "génétique Première Cameroun",
                "immunologie Première Cameroun",
            ],
        },
        "terminale": {
            "fr": [
                "SVT Terminale Cameroun",
                "Baccalauréat SVT Cameroun",
                "révision bac SVT Cameroun",
            ],
        },
        "form4_5": {
            "en": [
                "biology Form 4 Cameroon",
                "chemistry O-Level Cameroon",
                "GCE O-Level science Cameroon",
            ],
        },
        "lower6th": {
            "en": [
                "biology Lower 6th Cameroon",
                "GCE A-Level biology Cameroon",
                "genetics A-Level Cameroon",
            ],
        },
        "upper6th": {
            "en": [
                "biology Upper 6th Cameroon",
                "GCE A-Level science revision Cameroon",
                "A-Level past papers science Cameroon",
            ],
        },
    },
    "physique_chimie": {
        "troisieme": {
            "fr": [
                "physique chimie 3ème Cameroun",
                "BEPC physique Cameroun",
                "électricité 3ème Cameroun",
            ],
        },
        "premiere": {
            "fr": [
                "physique Première Cameroun",
                "Probatoire physique Cameroun",
                "chimie organique Première Cameroun",
            ],
        },
        "terminale": {
            "fr": [
                "physique Terminale Cameroun",
                "Baccalauréat physique Cameroun",
                "révision bac physique Cameroun",
            ],
        },
        "form4_5": {
            "en": [
                "physics Form 5 Cameroon",
                "chemistry O-Level Cameroon",
            ],
        },
        "lower6th": {
            "en": [
                "chemistry A-Level Cameroon",
                "GCE A-Level chemistry Cameroon",
            ],
        },
    },
    "francais_anglais": {
        "troisieme": {
            "fr": [
                "français 3ème Cameroun",
                "BEPC français Cameroun",
            ],
        },
        "premiere": {
            "fr": [
                "français Première Cameroun",
                "Probatoire français Cameroun",
            ],
        },
        "terminale": {
            "fr": [
                "Baccalauréat français Cameroun",
                "révision bac français Cameroun",
            ],
        },
        "form4_5": {
            "en": [
                "English language Form 4 Cameroon",
                "GCE O-Level English Cameroon",
            ],
        },
        "upper6th": {
            "en": [
                "GCE A-Level English Cameroon",
                "GCE A-Level literature Cameroon",
            ],
        },
    },
    "histoire_geo_eco": {
        "troisieme": {
            "fr": [
                "histoire géographie 3ème Cameroun",
                "BEPC histoire géo Cameroun",
            ],
        },
        "premiere": {
            "fr": [
                "histoire Première Cameroun",
                "Probatoire histoire géo Cameroun",
            ],
        },
        "terminale": {
            "fr": [
                "Baccalauréat histoire géo Cameroun",
                "économie Terminale Cameroun",
                "Baccalauréat économie Cameroun",
            ],
        },
        "form4_5": {
            "en": [
                "history Form 4 Cameroon",
                "GCE O-Level history Cameroon",
            ],
        },
        "upper6th": {
            "en": [
                "GCE A-Level history Cameroon",
                "GCE A-Level economics Cameroon",
            ],
        },
    },
}

# Paramètres de collecte
TARGET_COMMENTS            = 5000  # Objectif minimum de commentaires
MAX_RESULTATS_PAR_REQUETE  = 50    # Max par appel search.list (limite API : 50)
TAILLE_LOT_METADATA        = 50    # Taille des lots pour videos.list (max : 50)
MAX_COMMENTAIRES_PAR_VIDEO = 200   # Max commentaires collectés par vidéo

# Paramètres de filtrage (adaptés au contexte camerounais)
SEUIL_MIN_COMMENTAIRES = 5     # Vidéos avec moins de 5 commentaires éliminées
SEUIL_MIN_VUES         = 100   # Vidéos avec moins de 100 vues éliminées
DUREE_MIN_SECONDES     = 120   # Vidéos de moins de 2 min éliminées

# Paramètres de robustesse
DELAI_ENTRE_APPELS_SECONDES     = 0.5
MAX_TENTATIVES_API              = 3
DELAI_ENTRE_TENTATIVES_SECONDES = 2

# Répertoires et fichiers de sortie
from pathlib import Path
REPERTOIRE_DATA     = Path("data")
REPERTOIRE_DATA_RAW = REPERTOIRE_DATA / "raw"
REPERTOIRE_DATA.mkdir(parents=True, exist_ok=True)
REPERTOIRE_DATA_RAW.mkdir(parents=True, exist_ok=True)

FICHIER_RESULTATS_RECHERCHE_BRUTS      = REPERTOIRE_DATA_RAW / "search_results_raw.csv"
FICHIER_VIDEOS_CANDIDATES_DEDUPLIQUEES = REPERTOIRE_DATA_RAW / "videos_candidates_deduplicated.csv"
FICHIER_METADATA_VIDEOS                = REPERTOIRE_DATA_RAW / "videos_metadata.csv"
FICHIER_VIDEOS_SELECTIONNEES           = REPERTOIRE_DATA_RAW / "videos_selected.csv"
FICHIER_COMMENTAIRES_BRUTS             = REPERTOIRE_DATA_RAW / "comments_raw.csv"
FICHIER_CACHE_REQUETES                 = REPERTOIRE_DATA_RAW / "cache_requetes.json"
FICHIER_CACHE_VIDEOS_ENRICHIES         = REPERTOIRE_DATA_RAW / "cache_videos_enrichies.json"
FICHIER_CACHE_COMMENTAIRES             = REPERTOIRE_DATA_RAW / "cache_commentaires.json"

total_requetes = sum(
    len(requetes)
    for niveaux in REQUETES_PAR_THEMATIQUE.values()
    for langues in niveaux.values()
    for requetes in langues.values()
)
print("\n Configuration chargée — Contexte : Éducation Cameroun")
print(f"   Thématiques    : {list(REQUETES_PAR_THEMATIQUE.keys())}")
print(f"   Langues cibles : {LANGUES_CIBLES}")
print(f"   Requêtes total : {total_requetes}")
print(f"   Objectif comms : {TARGET_COMMENTS}")
print(f"   Répertoire     : {REPERTOIRE_DATA_RAW}")

 Configuration chargée
   Thématiques : ['informatique']
   Langues cibles : ['fr', 'en']
   Répertoire de données : data/raw

## 3 — Système de cache (persistance et reprise)

In [30]:
# SYSTÈME DE CACHE
# Permet de reprendre le pipeline sans répéter les appels déjà faits

def charger_cache(chemin_fichier: Path) -> Set[str]:
    """Charge un fichier de cache JSON. Retourne un set vide si inexistant."""
    if not chemin_fichier.exists():
        return set()
    try:
        with open(chemin_fichier, "r", encoding="utf-8") as f:
            return set(json.load(f))
    except (json.JSONDecodeError, IOError):
        return set()  # Fichier corrompu (cache vide)

def sauvegarder_cache(chemin_fichier: Path, ensemble: Set[str]) -> None:
    """Sauvegarde un set de clés dans un fichier JSON."""
    with open(chemin_fichier, "w", encoding="utf-8") as f:
        json.dump(list(ensemble), f, ensure_ascii=False, indent=2)

def ajouter_au_cache(chemin_fichier: Path, cle: str) -> None:
    """Ajoute une clé au cache et sauvegarde immédiatement."""
    cache = charger_cache(chemin_fichier)
    cache.add(cle)
    sauvegarder_cache(chemin_fichier, cache)

def est_dans_cache(chemin_fichier: Path, cle: str) -> bool:
    """Vérifie si une clé est déjà dans le cache."""
    return cle in charger_cache(chemin_fichier)

#  Fonctions de cache spécialisées 

def requete_deja_executee(thematique: str, langue: str, requete: str) -> bool:
    """Vérifie si une requête de recherche a déjà été exécutée."""
    cle = f"{thematique}|{langue}|{requete}"
    return est_dans_cache(FICHIER_CACHE_REQUETES, cle)

def marquer_requete_executee(thematique: str, langue: str, requete: str) -> None:
    """Marque une requête de recherche comme exécutée."""
    cle = f"{thematique}|{langue}|{requete}"
    ajouter_au_cache(FICHIER_CACHE_REQUETES, cle)

def video_deja_enrichie(video_id: str) -> bool:
    """Vérifie si les métadonnées d'une vidéo ont déjà été collectées."""
    return est_dans_cache(FICHIER_CACHE_VIDEOS_ENRICHIES, video_id)

def marquer_videos_enrichies(video_ids: List[str]) -> None:
    """Marque un lot de vidéos comme enrichies."""
    cache = charger_cache(FICHIER_CACHE_VIDEOS_ENRICHIES)
    for vid in video_ids:
        cache.add(vid)
    sauvegarder_cache(FICHIER_CACHE_VIDEOS_ENRICHIES, cache)

def commentaires_deja_collectes(video_id: str) -> bool:
    """Vérifie si les commentaires d'une vidéo ont déjà été collectés."""
    return est_dans_cache(FICHIER_CACHE_COMMENTAIRES, video_id)

def marquer_commentaires_collectes(video_id: str) -> None:
    """Marque une vidéo comme ayant ses commentaires collectés."""
    ajouter_au_cache(FICHIER_CACHE_COMMENTAIRES, video_id)

print("Système de cache initialisé")

# Affichage de l'état du cache actuel
nb_requetes_en_cache   = len(charger_cache(FICHIER_CACHE_REQUETES))
nb_videos_en_cache     = len(charger_cache(FICHIER_CACHE_VIDEOS_ENRICHIES))
nb_comments_en_cache   = len(charger_cache(FICHIER_CACHE_COMMENTAIRES))
print(f"   Requêtes en cache     : {nb_requetes_en_cache}")
print(f"   Vidéos enrichies      : {nb_videos_en_cache}")
print(f"   Vidéos commentées     : {nb_comments_en_cache}")

Système de cache initialisé
   Requêtes en cache     : 16
   Vidéos enrichies      : 716
   Vidéos commentées     : 413

## 4 — Fonctions utilitaires

In [31]:
# FONCTIONS UTILITAIRES

def configurer_logger(nom: str) -> logging.Logger:
    """Configure et retourne un logger formaté."""
    logger = logging.getLogger(nom)
    if not logger.handlers:
        logger.setLevel(logging.INFO)
        handler = logging.StreamHandler(sys.stdout)
        handler.setFormatter(logging.Formatter(
            "[%(asctime)s] %(levelname)s — %(message)s",
            datefmt="%H:%M:%S"
        ))
        logger.addHandler(handler)
    return logger

logger = configurer_logger("collecte")

def convertir_duree_iso_en_secondes(duree_iso: str) -> int:
    """
    Convertit une durée ISO 8601 en secondes.
    Exemples : 'PT4M33S' → 273 | 'PT1H2M5S' → 3725 | 'PT15S' → 15
    """
    if not duree_iso:
        return 0
    pattern = r"PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?"
    match = re.match(pattern, duree_iso)
    if not match:
        return 0
    heures   = int(match.group(1) or 0)
    minutes  = int(match.group(2) or 0)
    secondes = int(match.group(3) or 0)
    return heures * 3600 + minutes * 60 + secondes

def construire_url_youtube(video_id: str) -> str:
    """Retourne l'URL YouTube complète à partir d'un video_id."""
    return f"https://www.youtube.com/watch?v={video_id}"

# ─── Tests unitaires rapides ───────────────────────────────────────────
assert convertir_duree_iso_en_secondes("PT4M33S")  == 273
assert convertir_duree_iso_en_secondes("PT1H2M5S") == 3725
assert convertir_duree_iso_en_secondes("PT15S")    == 15
assert convertir_duree_iso_en_secondes("")         == 0

print(" Fonctions utilitaires opérationnelles (tests réussis)")

 Fonctions utilitaires opérationnelles (tests réussis)

## 5 — Couche d'accès à l'API YouTube

In [32]:

# COUCHE D'ACCÈS API — FONCTION PRINCIPALE D'APPEL HTTP

def executer_requete_api(endpoint: str, parametres: dict) -> Optional[dict]:
    """
    Exécute un appel GET vers l'API YouTube avec gestion des erreurs et retries.
    
    Codes d'erreur gérés :
      - 200 : succès
      - 400 : paramètres invalides (arrêt sans retry)
      - 403 : quota dépassé ou clé invalide (arrêt sans retry)
      - 429 / 503 : rate limiting ou indispo temporaire (retry avec délai)
    """
    parametres_complets = {"key": YOUTUBE_API_KEY, **parametres}

    for tentative in range(1, MAX_TENTATIVES_API + 1):
        time.sleep(DELAI_ENTRE_APPELS_SECONDES)

        try:
            reponse = requests.get(endpoint, params=parametres_complets, timeout=15)

            if reponse.status_code == 200:
                return reponse.json()

            elif reponse.status_code == 403:
                raison = reponse.json().get("error", {}).get("message", "?")
                logger.error(f" Accès refusé (403) : {raison}")
                return None  
            elif reponse.status_code == 400:
                raison = reponse.json().get("error", {}).get("message", "?")
                logger.error(f" Requête invalide (400) : {raison}")
                return None  
            elif reponse.status_code in (429, 503):
                logger.warning(f" Code {reponse.status_code} — retry {tentative}/{MAX_TENTATIVES_API}")
                time.sleep(DELAI_ENTRE_TENTATIVES_SECONDES)

            else:
                logger.warning(f" HTTP {reponse.status_code} — retry {tentative}/{MAX_TENTATIVES_API}")
                time.sleep(DELAI_ENTRE_TENTATIVES_SECONDES)

        except requests.exceptions.Timeout:
            logger.warning(f"  Timeout — retry {tentative}/{MAX_TENTATIVES_API}")
            time.sleep(DELAI_ENTRE_TENTATIVES_SECONDES)

        except requests.exceptions.ConnectionError as e:
            logger.warning(f"  Erreur réseau : {e} — retry {tentative}/{MAX_TENTATIVES_API}")
            time.sleep(DELAI_ENTRE_TENTATIVES_SECONDES)

    logger.error(f" Échec après {MAX_TENTATIVES_API} tentatives : {endpoint}")
    return None


#  Fonctions API spécialisées 

def api_rechercher_videos(requete: str, langue: str, max_resultats: int = 50) -> Optional[dict]:
    """Appelle search.list. Coût : 100 unités de quota. À minimiser """
    return executer_requete_api(ENDPOINT_SEARCH, {
        "q":                 requete,
        "part":              "snippet",
        "type":              "video",
        "maxResults":        min(max_resultats, 50),
        "relevanceLanguage": langue,
        "safeSearch":        "moderate",
    })

def api_metadata_videos_batch(lot_video_ids: List[str]) -> Optional[dict]:
    """Appelle videos.list pour un lot de 50 vidéos max. Coût : 1 unité."""
    return executer_requete_api(ENDPOINT_VIDEOS, {
        "id":   ",".join(lot_video_ids[:50]),
        "part": "snippet,statistics,contentDetails",
    })

def api_commentaires_page(
    video_id: str,
    max_resultats: int = 100,
    jeton_page: Optional[str] = None
) -> Optional[dict]:
    """Appelle commentThreads.list. Coût : 1 unité."""
    params = {
        "videoId":    video_id,
        "part":       "snippet",
        "maxResults": min(max_resultats, 100),
        "order":      "relevance",  # Commentaires les plus utiles en premier
    }
    if jeton_page:
        params["pageToken"] = jeton_page
    return executer_requete_api(ENDPOINT_COMMENT_THREADS, params)

print(" Couche d'accès API configurée")
print(f"   Endpoint search  : {ENDPOINT_SEARCH}")
print(f"   Endpoint videos  : {ENDPOINT_VIDEOS}")
print(f"   Endpoint comments: {ENDPOINT_COMMENT_THREADS}")

 Couche d'accès API configurée
   Endpoint search  : https://www.googleapis.com/youtube/v3/search
   Endpoint videos  : https://www.googleapis.com/youtube/v3/videos
   Endpoint comments: https://www.googleapis.com/youtube/v3/commentThreads

In [33]:
# import json

# with open(FICHIER_CACHE_REQUETES, "w", encoding="utf-8") as f:
#     json.dump({}, f, indent=4, ensure_ascii=False)

# print(" Cache des requêtes réinitialisé")

##  6 — Phase B : Recherche des vidéos candidates

In [34]:
# PHASE B — RECHERCHE DES VIDÉOS CANDIDATES (search.list)
# Coût quota : 100 unités par requête — à minimiser absolument

COLONNES_RECHERCHE = ["video_id","titre","chaine","channel_id","publie_le","requete_utilisee","langue","thematique","level"]

def executer_phase_recherche() -> pd.DataFrame:
    """Exécute toutes les requêtes de recherche par thématique, niveau et langue."""

    logger.info(" Phase B — Recherche des vidéos candidates")

    toutes_requetes = [
        (thematique, level, langue, requete)
        for thematique, niveaux in REQUETES_PAR_THEMATIQUE.items()
        for level, langues in niveaux.items()
        for langue, requetes in langues.items()
        for requete in requetes
    ]

    logger.info(f" {len(toutes_requetes)} requêtes planifiées")
    nb_nouvelles = 0

    for thematique, level, langue, requete in tqdm(toutes_requetes, desc="Recherche vidéos"):

        if requete_deja_executee(thematique, langue, requete):
            print(" Requête ignorée (déjà exécutée)")
            continue

        reponse = api_rechercher_videos(requete, langue, MAX_RESULTATS_PAR_REQUETE)
        marquer_requete_executee(thematique, langue, requete)

        if not reponse:
            continue

        lignes = []
        for item in reponse.get("items", []):
            if item.get("id", {}).get("kind") != "youtube#video":
                continue
            try:
                lignes.append({
                    "video_id":         item["id"]["videoId"],
                    "titre":            item["snippet"].get("title", ""),
                    "chaine":           item["snippet"].get("channelTitle", ""),
                    "channel_id":       item["snippet"].get("channelId", ""),
                    "publie_le":        item["snippet"].get("publishedAt", ""),
                    "requete_utilisee": requete,
                    "langue":           langue,
                    "thematique":       thematique,
                    "level":            level,
                })
            except (KeyError, TypeError):
                continue

        if lignes:
            df_batch = pd.DataFrame(lignes, columns=COLONNES_RECHERCHE)
            mode = "a" if FICHIER_RESULTATS_RECHERCHE_BRUTS.exists() else "w"
            df_batch.to_csv(FICHIER_RESULTATS_RECHERCHE_BRUTS, mode=mode,
                           header=(mode=="w"), index=False, encoding="utf-8")
            nb_nouvelles += len(lignes)

    if FICHIER_RESULTATS_RECHERCHE_BRUTS.exists():
        df = pd.read_csv(FICHIER_RESULTATS_RECHERCHE_BRUTS, encoding="utf-8")
        logger.info(f" Phase B terminée : {len(df)} vidéos candidates ({nb_nouvelles} nouvelles)")
        return df
    return pd.DataFrame(columns=COLONNES_RECHERCHE)


# EXÉCUTION
df_resultats_bruts = executer_phase_recherche()
print(f"\n Résultats bruts : {len(df_resultats_bruts)} lignes")
df_resultats_bruts.head()

[21:54:42] INFO —  Phase B — Recherche des vidéos candidates
[21:54:42] INFO —  16 requêtes planifiées

Recherche vidéos: 100%|██████████| 16/16 [00:00<00:00, 4071.65it/s]

 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
 Requête ignorée (déjà exécutée)
[21:54:42] INFO —  Phase B terminée : 777 vidéos candidates (0 nouvelles)

 Résultats bruts : 777 lignes

,video_id,titre,chaine,publie_le,requete_utilisee,langue,thematique
0,oUJolR5bX6g,APPRENDRE PYTHON [TUTO PROGRAMMATION COMPLET D...,CodeAvecJonathan,2020-10-17T07:17:34Z,cours programmation Python,fr,informatique
1,PmpheCTL6yk,"Python, c&#39;est quoi ?",Informatique Sans Complexe !,2021-09-27T05:00:07Z,cours programmation Python,fr,informatique
2,5EnpNI2iCZA,Apprendre Python en 1 heure - Cours Complet Dé...,Comment Coder,2024-02-19T17:30:00Z,cours programmation Python,fr,informatique
3,psaDHhZ0cPs,APPRENDRE LE PYTHON #1 ? LES BASES &amp; PRERE...,Graven - Développement,2018-05-07T19:00:03Z,cours programmation Python,fr,informatique
4,_TVrC_HCkTE,Apprendre Python - Programmation Python pour D...,MaxCode,2022-12-24T06:00:11Z,cours programmation Python,fr,informatique

##  7 — Phase C : Déduplication des vidéos

In [35]:
# PHASE C — DÉDUPLICATION SUR video_id


logger.info(" Phase C — Déduplication des vidéos")

nb_avant = len(df_resultats_bruts)
df_deduplique = df_resultats_bruts.drop_duplicates(subset=["video_id"], keep="first").reset_index(drop=True)
nb_apres  = len(df_deduplique)

logger.info(f" {nb_avant}  {nb_apres} vidéos ({nb_avant - nb_apres} doublons supprimés)")

# Sauvegarde
df_deduplique.to_csv(FICHIER_VIDEOS_CANDIDATES_DEDUPLIQUEES, index=False, encoding="utf-8")
logger.info(f" Sauvegardé  {FICHIER_VIDEOS_CANDIDATES_DEDUPLIQUEES.name}")

# Affichage répartition
print("\n Répartition après déduplication :")
print(df_deduplique.groupby(["thematique","langue"]).size().reset_index(name="nb_videos").to_string(index=False))

[21:55:21] INFO —  Phase C — Déduplication des vidéos
[21:55:21] INFO —  777  716 vidéos (61 doublons supprimés)
[21:55:21] INFO —  Sauvegardé  videos_candidates_deduplicated.csv

 Répartition après déduplication :
  thematique langue  nb_videos
informatique     en        360
informatique     fr        356

## 8 — Phase D : Enrichissement batch des métadonnées

In [36]:
# PHASE D — ENRICHISSEMENT BATCH (videos.list)
# 1 appel pour 50 vidéos = économie massive de quota

COLONNES_METADATA = [
    "video_id","video_url","titre","chaine","channel_id","publie_le",
    "categorie_id","description","nb_vues","nb_likes",
    "nb_commentaires","duree_iso","duree_secondes","langue","thematique",
    "system","level"
]

def executer_phase_metadata(df_candidates: pd.DataFrame) -> pd.DataFrame:
    """Enrichit toutes les vidéos candidates en batch (50 vidéos par appel)."""

    logger.info(" Phase D — Enrichissement batch des métadonnées")

    # Mapping video_id → (langue, thematique, channel_id, level)
    mapping = {
        row["video_id"]: (
            row["langue"],
            row["thematique"],
            row.get("channel_id", ""),
            row.get("level", ""),
        )
        for _, row in df_candidates.iterrows()
    }

    videos_a_traiter = [vid for vid in df_candidates["video_id"].tolist() if not video_deja_enrichie(vid)]
    logger.info(f" {len(videos_a_traiter)}/{len(df_candidates)} vidéos à enrichir")

    lots = [videos_a_traiter[i:i+TAILLE_LOT_METADATA] for i in range(0, len(videos_a_traiter), TAILLE_LOT_METADATA)]
    logger.info(f" {len(lots)} lot(s) de {TAILLE_LOT_METADATA} vidéos")

    for i, lot in enumerate(tqdm(lots, desc="Enrichissement batch"), 1):
        reponse = api_metadata_videos_batch(lot)
        if not reponse:
            continue

        lignes = []
        for item in reponse.get("items", []):
            try:
                vid_id    = item["id"]
                snippet   = item.get("snippet", {})
                stats     = item.get("statistics", {})
                details   = item.get("contentDetails", {})
                duree_iso = details.get("duration", "")
                langue, thematique, channel_id, level = mapping.get(vid_id, ("inconnu", "inconnu", "", ""))
                system = "francophone" if langue == "fr" else "anglophone"

                lignes.append({
                    "video_id":        vid_id,
                    "video_url":       construire_url_youtube(vid_id),
                    "titre":           snippet.get("title", ""),
                    "chaine":          snippet.get("channelTitle", ""),
                    "channel_id":      channel_id,
                    "publie_le":       snippet.get("publishedAt", ""),
                    "categorie_id":    snippet.get("categoryId", ""),
                    "description":     snippet.get("description", "")[:300],
                    "nb_vues":         int(stats.get("viewCount", 0)),
                    "nb_likes":        int(stats.get("likeCount", 0)),
                    "nb_commentaires": int(stats.get("commentCount", 0)),
                    "duree_iso":       duree_iso,
                    "duree_secondes":  convertir_duree_iso_en_secondes(duree_iso),
                    "langue":          langue,
                    "thematique":      thematique,
                    "system":          system,
                    "level":           level,
                })
            except (KeyError, TypeError, ValueError):
                continue

        if lignes:
            df_lot = pd.DataFrame(lignes, columns=COLONNES_METADATA)
            mode = "a" if FICHIER_METADATA_VIDEOS.exists() else "w"
            df_lot.to_csv(FICHIER_METADATA_VIDEOS, mode=mode,
                         header=(mode=="w"), index=False, encoding="utf-8")

        marquer_videos_enrichies(lot)
        logger.info(f"  Lot {i}/{len(lots)} — {len(lignes)} métadonnées sauvegardées")

    if FICHIER_METADATA_VIDEOS.exists():
        df = pd.read_csv(FICHIER_METADATA_VIDEOS, encoding="utf-8")
        logger.info(f" Phase D terminée : {len(df)} vidéos enrichies")
        return df
    return pd.DataFrame(columns=COLONNES_METADATA)


# EXÉCUTION
df_metadata = executer_phase_metadata(df_deduplique)
print(f"\n Métadonnées collectées : {len(df_metadata)} vidéos")
df_metadata[["titre","nb_vues","nb_commentaires","duree_secondes","langue","thematique","system","level","channel_id"]].head(10)

[21:59:45] INFO —  Phase D — Enrichissement batch des métadonnées
[21:59:45] INFO —  0/716 vidéos à enrichir
[21:59:45] INFO —  0 lot(s) de 50 vidéos

Enrichissement batch: 0it [00:00, ?it/s]

[21:59:46] INFO —  Phase D terminée : 716 vidéos enrichies

 Métadonnées collectées : 716 vidéos

,titre,nb_vues,nb_commentaires,duree_secondes,langue,thematique
0,APPRENDRE PYTHON [TUTO PROGRAMMATION COMPLET D...,3956180,4000,8173,fr,informatique
1,"Python, c'est quoi ?",50095,56,229,fr,informatique
2,Apprendre Python en 1 heure - Cours Complet Dé...,488134,452,3601,fr,informatique
3,APPRENDRE LE PYTHON #1 ? LES BASES & PREREQUIS,2965079,1559,567,fr,informatique
4,Apprendre Python - Programmation Python pour D...,234463,456,16943,fr,informatique
5,Apprenez Python de Zéro : La Formation Complèt...,76597,202,7728,fr,informatique
6,Python - Cours complet pour débutants (2026),5911,29,9524,fr,informatique
7,4 Techniques pour Apprendre à Coder EFFICACEMENT,139835,250,401,fr,informatique
8,APPRENDRE PYTHON DE A à Z,1997197,1657,25068,fr,informatique
9,Programmation Python - SNT - Seconde - Les Bon...,63317,14,300,fr,informatique

##  9 — Phase E : Filtrage des vidéos

In [37]:
# PHASE E — FILTRAGE DES VIDÉOS PEU EXPLOITABLES
# Filtrer AVANT de collecter les commentaires = économie de quota


logger.info(" Phase E — Filtrage des vidéos")

df_filtre = df_metadata.copy()

# Conversion numérique sécurisée
for col in ["nb_commentaires", "nb_vues", "duree_secondes"]:
    df_filtre[col] = pd.to_numeric(df_filtre[col], errors="coerce").fillna(0)

nb_initial = len(df_filtre)

# Règle F1 : commentaires minimum
df_filtre = df_filtre[df_filtre["nb_commentaires"] >= SEUIL_MIN_COMMENTAIRES]
logger.info(f"F1 (≥{SEUIL_MIN_COMMENTAIRES} commentaires) : {nb_initial} → {len(df_filtre)}")

#  Règle F2 : vues minimum 
n2 = len(df_filtre)
df_filtre = df_filtre[df_filtre["nb_vues"] >= SEUIL_MIN_VUES]
logger.info(f"F2 (≥{SEUIL_MIN_VUES} vues)      : {n2} → {len(df_filtre)}")

#  Règle F3 : durée minimale 
n3 = len(df_filtre)
df_filtre = df_filtre[df_filtre["duree_secondes"] >= DUREE_MIN_SECONDES]
logger.info(f"F3 (≥{DUREE_MIN_SECONDES}s durée)      : {n3} → {len(df_filtre)}")

df_filtre = df_filtre.reset_index(drop=True)
df_filtre.to_csv(FICHIER_VIDEOS_SELECTIONNEES, index=False, encoding="utf-8")

logger.info(f" Phase E terminée : {nb_initial} → {len(df_filtre)} vidéos retenues")
logger.info(f" Sauvegardé → {FICHIER_VIDEOS_SELECTIONNEES.name}")

print("\n Répartition des vidéos sélectionnées :")
print(df_filtre.groupby(["thematique","langue"]).size().reset_index(name="nb_videos").to_string(index=False))

[22:00:38] INFO —  Phase E — Filtrage des vidéos
[22:00:38] INFO — F1 (≥20 commentaires) : 716 → 514
[22:00:38] INFO — F2 (≥500 vues)      : 514 → 513

[22:00:38] INFO — F3 (≥60s durée)      : 513 → 413
[22:00:38] INFO —  Phase E terminée : 716 → 413 vidéos retenues
[22:00:38] INFO —  Sauvegardé → videos_selected.csv

 Répartition des vidéos sélectionnées :
  thematique langue  nb_videos
informatique     en        233
informatique     fr        180

##  10 — Phase F : Collecte des commentaires

In [38]:
# PHASE F — COLLECTE DES COMMENTAIRES (commentThreads.list)
# Uniquement pour les vidéos retenues après filtrage


COLONNES_COMMENTAIRES = [
    "commentaire_id","video_id","texte_commentaire",
    "publie_le","nb_likes_commentaire","nb_reponses"
]

def collecter_commentaires_une_video(video_id: str) -> List[Dict]:
    """Collecte les commentaires top-level d'une vidéo avec pagination contrôlée."""
    commentaires   = []
    jeton_page     = None
    continuer      = True

    while continuer:
        nb_restants = MAX_COMMENTAIRES_PAR_VIDEO - len(commentaires)
        if nb_restants <= 0:
            break

        reponse = api_commentaires_page(video_id, min(nb_restants, 100), jeton_page)
        if not reponse:
            break  # Commentaires désactivés ou erreur → passer

        for item in reponse.get("items", []):
            try:
                snippet_top = item["snippet"]["topLevelComment"]["snippet"]
                texte = snippet_top.get("textDisplay", "").strip()
                if len(texte) < 3:
                    continue  # Ignorer les commentaires trop courts

                commentaires.append({
                    "commentaire_id":       item["id"],
                    "video_id":             video_id,
                    "texte_commentaire":    texte,
                    "publie_le":            snippet_top.get("publishedAt", ""),
                    "nb_likes_commentaire": int(snippet_top.get("likeCount", 0)),
                    "nb_reponses":          int(item["snippet"].get("totalReplyCount", 0)),
                })
            except (KeyError, TypeError):
                continue

            if len(commentaires) >= MAX_COMMENTAIRES_PAR_VIDEO:
                continuer = False
                break

        jeton_page = reponse.get("nextPageToken")
        if not jeton_page:
            continuer = False

    return commentaires


def executer_phase_commentaires(df_videos: pd.DataFrame) -> pd.DataFrame:
    """Collecte les commentaires pour toutes les vidéos sélectionnées."""

    logger.info("Phase F — Collecte des commentaires")

    video_ids = df_videos["video_id"].tolist()
    a_traiter = [v for v in video_ids if not commentaires_deja_collectes(v)]
    logger.info(f" {len(a_traiter)}/{len(video_ids)} vidéos à traiter")

    nb_total = 0

    for video_id in tqdm(a_traiter, desc="Collecte commentaires"):
        commentaires = collecter_commentaires_une_video(video_id)
        marquer_commentaires_collectes(video_id)  

        if commentaires:
            df_comm = pd.DataFrame(commentaires, columns=COLONNES_COMMENTAIRES)
            mode = "a" if FICHIER_COMMENTAIRES_BRUTS.exists() else "w"
            df_comm.to_csv(FICHIER_COMMENTAIRES_BRUTS, mode=mode,
                          header=(mode=="w"), index=False, encoding="utf-8")
            nb_total += len(commentaires)

    if FICHIER_COMMENTAIRES_BRUTS.exists():
        df = pd.read_csv(FICHIER_COMMENTAIRES_BRUTS, encoding="utf-8")
        logger.info(f" Phase F terminée : {len(df)} commentaires collectés")
        return df
    return pd.DataFrame(columns=COLONNES_COMMENTAIRES)


#  EXÉCUTION 
df_commentaires = executer_phase_commentaires(df_filtre)
print(f"\n Commentaires collectés : {len(df_commentaires)}")
df_commentaires.head(10)

[22:00:49] INFO — Phase F — Collecte des commentaires

[22:00:49] INFO —  0/413 vidéos à traiter

Collecte commentaires: 0it [00:00, ?it/s]

[22:00:50] INFO —  Phase F terminée : 31182 commentaires collectés

 Commentaires collectés : 31182

,commentaire_id,video_id,texte_commentaire,publie_le,nb_likes_commentaire,nb_reponses
0,UgxaFGI_QvZxcdd4kph4AaABAg,oUJolR5bX6g,"👉La formation complète (600 vidéos, plus de 60...",2020-10-17T07:26:55Z,358.0,164.0
1,Ugy4rM4TKnesmvYRZX14AaABAg,oUJolR5bX6g,"Incroyable, vous avez fait aimer et appris la ...",2024-03-20T07:27:49Z,166.0,8.0
2,UgyjamduXo0d0y5nEPF4AaABAg,oUJolR5bX6g,Je suis SUBJUGUE par la qualité de ce contenu!...,2021-01-17T19:34:15Z,960.0,4.0
3,UgxMv26LwnrxZKVuSex4AaABAg,oUJolR5bX6g,Même si j&#39;ai que 12 ans j&#39;ai à peu prè...,2022-06-28T13:28:05Z,378.0,46.0
4,Ugzu42Me9982Dkijn0h4AaABAg,oUJolR5bX6g,"L&#39;exercice 1 j&#39;ai réussi, je pratique ...",2026-02-15T13:34:47Z,14.0,0.0
5,UgwOUNAweAhjrxRjPMh4AaABAg,oUJolR5bX6g,"Bonjour, je viens du Bénin(Afrique de l&#39;Ou...",2021-09-02T15:37:53Z,56.0,1.0
6,UgxY2aYJsfLDAg1oyJR4AaABAg,oUJolR5bX6g,Super! J&#39;avais horreur des tutoriels vidéo...,2024-04-13T09:59:18Z,58.0,1.0
7,Ugy3L0Y1v1IfAc21Jqp4AaABAg,oUJolR5bX6g,En tout cas pour moi c&#39;est simplement pass...,2023-04-14T16:57:44Z,4.0,0.0
8,UgzJywu8X6Q50_M6-qt4AaABAg,oUJolR5bX6g,vidéos vraiment complète et super bien. quelle...,2026-03-31T17:45:44Z,0.0,0.0
9,Ugx04NqFPhKiu8KeqyV4AaABAg,oUJolR5bX6g,vraiment c`est une formation exceptionnelle; a...,2023-01-09T13:31:53Z,8.0,0.0

##   11 — Résumé et vérification du dataset final

In [39]:

# RÉSUMÉ FINAL DE LA COLLECTE


print("=" * 55)
print("   RÉSUMÉ DE LA COLLECTE")
print("=" * 55)
print(f"  Vidéos candidates (brutes)     : {len(df_resultats_bruts)}")
print(f"  Vidéos après déduplication     : {len(df_deduplique)}")
print(f"  Vidéos enrichies (métadonnées) : {len(df_metadata)}")
print(f"  Vidéos sélectionnées (filtrées): {len(df_filtre)}")
print(f"  Commentaires collectés         : {len(df_commentaires)}")
print("=" * 55)

#  Vérification des fichiers produits 
print("\n Fichiers produits :")
for fichier in [
    FICHIER_RESULTATS_RECHERCHE_BRUTS,
    FICHIER_VIDEOS_CANDIDATES_DEDUPLIQUEES,
    FICHIER_METADATA_VIDEOS,
    FICHIER_VIDEOS_SELECTIONNEES,
    FICHIER_COMMENTAIRES_BRUTS,
]:
    taille = fichier.stat().st_size / 1024 if fichier.exists() else 0
    statut = "OKK" if fichier.exists() else "NOO"
    print(f"  {statut} {fichier.name:<50} ({taille:.1f} Ko)")

# Aperçu du dataset commentaires final 
print("\n Aperçu du dataset de commentaires :")
print(f"   Colonnes : {list(df_commentaires.columns)}")
print(f"   Taille   : {df_commentaires.shape}")
print(f"   Mémoire  : {df_commentaires.memory_usage().sum() / 1024:.1f} Ko")

# Distribution des commentaires par vidéo 
if not df_commentaires.empty:
    stats_par_video = df_commentaires.groupby("video_id")["texte_commentaire"].count()
    print(f"\n Distribution commentaires/vidéo :")
    print(f"   Min    : {stats_par_video.min()}")
    print(f"   Médiane: {stats_par_video.median():.1f}")
    print(f"   Max    : {stats_par_video.max()}")
    print(f"   Moyenne: {stats_par_video.mean():.1f}")

=======================================================
   RÉSUMÉ DE LA COLLECTE
=======================================================
  Vidéos candidates (brutes)     : 777
  Vidéos après déduplication     : 716
  Vidéos enrichies (métadonnées) : 716
  Vidéos sélectionnées (filtrées): 413
  Commentaires collectés         : 31182
=======================================================

 Fichiers produits :
  OKK search_results_raw.csv                             (119.4 Ko)
  OKK videos_candidates_deduplicated.csv                 (110.4 Ko)
  OKK videos_metadata.csv                                (332.9 Ko)
  OKK videos_selected.csv                                (202.9 Ko)
  OKK comments_raw.csv                                   (6078.9 Ko)

 Aperçu du dataset de commentaires :
   Colonnes : ['commentaire_id', 'video_id', 'texte_commentaire', 'publie_le', 'nb_likes_commentaire', 'nb_reponses']
   Taille   : (31182, 6)
   Mémoire  : 1461.8 Ko

 Distribution commentaires/vidéo :
   Min    : 1
   Médiane: 100.0
   Max    : 100
   Moyenne: 67.2


##  Collecte terminée

Next step : 02 — Preprocessing 

| Fichier | Contenu |
|---|---|
| `videos_metadata.csv` | Métadonnées complètes des vidéos sélectionnées |
| `comments_raw.csv` | Commentaires bruts à analyser |
| **Réalisée par**| ***Kevin***|
|**Email institutionnelle**| stive.watat@facsciences-uy1.cm|
|**Email personnel**|   stivekevinwatatyondep@gmail.com| 

**Prochaine étape** : `02_preprocessing_and_noise.ipynb`( Nettoyage et filtrage du bruit)